// User
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

// User -> Account
export const SET_LOGIN_LOADER = 'SET_LOGIN_LOADER';
export const SET_ACCOUNT_LOADER = 'SET_ACCOUNT_LOADER';
export const SET_CREDITS = 'SET_CREDITS';
export const SET_LOGS = 'SET_LOGS';
export const CLEAR_LOGS = 'CLEAR_LOGS';
export const SET_ONLINE = 'SET_ONLINE';
export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO';

// User -> Character
export const SET_CHARACTER_LOADER = 'SET_CHARACTER_LOADER';
export const SET_CHARACTERS = 'SET_CHARACTERS';

// User -> Extra
export const SET_EXTRA_LOADER = 'SET_EXTRA_LOADER';
export const WAREHOUSE_UNLOCK = 'WAREHOUSE_UNLOCK';
export const WAREHOUSE_UPDATE = 'WAREHOUSE_UPDATE';
export const STORAGE_UPDATE = 'STORAGE_UPDATE';

// Rankings
export const GET_HOF = 'GET_HOF';
export const GET_HOF_FAILED = 'GET_HOF_FAILED';
export const GET_RANK_5GUILDS = 'GET_RANK_5GUILDS';
export const GET_RANK_5GUILDS_FAILED = 'GET_RANK_5GUILDS_FAILED';
export const GET_RANK_CHARACTERS = 'GET_RANK_CHARACTERS';
export const GET_RANK_CHARACTERS_FAILED = 'GET_RANK_CHARACTERS_FAILED';
export const CLEAR_RANK_CHARACTERS = 'CLEAR_RANK_CHARACTERS';
export const RANKINGS_LOADING = 'RANKINGS_LOADING';

// Others
export const MARKET_LATEST = 'MARKET_LATEST';
export const MARKET_LATEST_FAILED = 'MARKET_LATEST_FAILED';

// Config
export const SET_CONFIG = 'SET_CONFIG';
export const SET_CONFIG_FAILED = 'SET_CONFIG_FAILED';
