// User
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

// User -> Account
export const SET_ACCOUNT_LOADER = 'SET_ACCOUNT_LOADER';

// User -> Character
export const SET_CHARACTER_LOADER = 'SET_CHARACTER_LOADER';
export const SET_CHARACTERS = 'SET_CHARACTERS';

// User -> Extra
export const SET_EXTRA_LOADER = 'SET_EXTRA_LOADER';
export const WAREHOUSE_MOVE_ITEM = 'WAREHOUSE_MOVE_ITEM';
export const WAREHOUSE_UNLOCK = 'WAREHOUSE_UNLOCK';

// Rankings
export const GET_HOF = 'GET_HOF';
export const GET_HOF_FAILED = 'GET_HOF_FAILED';
export const GET_RANK_5GUILDS = 'GET_RANK_5GUILDS';
export const GET_RANK_5GUILDS_FAILED = 'GET_RANK_5GUILDS_FAILED';
export const GET_RANK_CHARACTERS = 'GET_RANK_CHARACTERS';
export const GET_RANK_CHARACTERS_FAILED = 'GET_RANK_CHARACTERS_FAILED';
export const CLEAR_RANK_CHARACTERS = 'CLEAR_RANK_CHARACTERS';

// Others
export const MARKET_LATEST = 'MARKET_LATEST';
export const MARKET_LATEST_FAILED = 'MARKET_LATEST_FAILED';

// Config
export const CONFIG_EVENTS = 'CONFIG_EVENTS';
export const CONFIG_EVENTS_FAILED = 'CONFIG_EVENTS_FAILED';
