// User
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

// Rankings
export const GET_HOF = 'GET_HOF';
export const GET_HOF_FAILED = 'GET_HOF_FAILED';
export const GET_RANK_5GUILDS = 'GET_RANK_5GUILDS';
export const GET_RANK_5GUILDS_FAILED = 'GET_RANK_5GUILDS_FAILED';
export const GET_RANK_CHARACTERS = 'GET_RANK_CHARACTERS';
export const GET_RANK_CHARACTERS_FAILED = 'GET_RANK_CHARACTERS_FAILED';
export const CLEAR_RANK_CHARACTERS = 'CLEAR_RANK_CHARACTERS';

// Others
export const MARKET_LATEST = 'MARKET_LATEST';
export const MARKET_LATEST_FAILED = 'MARKET_LATEST_FAILED';

// Config
export const CONFIG_EVENTS = 'CONFIG_EVENTS';
export const CONFIG_EVENTS_FAILED = 'CONFIG_EVENTS_FAILED';
